name: Change proposal v2
description: Propose an change for anything related to TampereJS
title: ""
labels: ["triage"]
body:
  # - type: markdown
  #   attributes:
  #     value: |
  #       Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A short description of the change that allows anyone to understand the change immediately.
      # placeholder: ex. email@example.com
    validations:
      required: true
  - type: textarea
    id: value
    attributes:
      label: What value does this change add towards the mission and the scope of it? (S/M/L)
      description: A clear and concise description of what value and the scope of it.
      # placeholder: Tell us what you see!
      # value: "A bug happened!"
    validations:
      required: true
  - type: textarea
    id: required-for-value
    attributes:
      label: What is required for this change to deliver value?
      description: List of most important things that are required for this change to deliver value.
      # options:
      #   - 1.0.2 (Default)
      #   - 1.0.3 (Edge)
    validations:
      required: true
  - type: textarea
    id: value-measurement
    attributes:
      label: How is the value measured?
      description: Clear and undertandable way to measure the value the change when delivered.
      # multiple: true
      # options:
      #   - Firefox
      #   - Chrome
      #   - Safari
      #   - Microsoft Edge
    validations:
      required: true
  - type: textarea
    id: definition-of-ready
    attributes:
      label: What needs to be defined for the implementation? (Definition of Ready)
      description: Change should have close to zero dependencies (common requirement)
      # render: shell
    validations:
      required: true
  - type: textarea
    id: definition-of-done
    attributes:
      label: What (automated) tests need to pass for this change? (Definition of Done)
      description: Clear and understandable list of tests that need to pass in order for this change to be considered
done.
    validations:
      required: true
  - type: textarea
    id: module-and-interfaces
    attributes:
      label: Which module is this change in and what other module interfaces are affected?
      description: Name of the module this change is isolated to and any other module interfaces affected.
    validations:
      required: true
  - type: textarea
    id: other-context
    attributes:
      label: Other context
      description: Add any other context or screenshots about the change proposal.
    validations:
      required: true
  # - type: checkboxes
  #   id: terms
  #   attributes:
  #     label: Code of Conduct
  #     description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
  #     options:
  #       - label: I agree to follow this project's Code of Conduct
  #         required: true